.PHONY: install start help # If you don't set this up, the system will prioritize matching files with these names, instead of our custom commands.

install:
	npm install

start:
	num run start

help:
	@echo "   	"
	@echo "    install"
	@echo "        Install all dependencies"
	@echo "    start"
	@echo "        Start this application"
