# squirrel.custom.yaml
patch:
  # us_keyboard_layout: true         # 键盘选项：应用美式键盘布局
  # show_notifications_when: growl_is_running  # 狀態通知，默認裝有Growl時顯示，也可設爲全開（always）全關（never）
    style/horizontal: true           # 候选窗横向显示
    style/inline_preedit: false   # 关闭内嵌编码，这样就可以显示首行的拼音（MAC下不建议开启）
    style/corner_radius: 3           # 窗口圆角半径
    style/border_height: 4           # 窗口边界高度，大于圆角半径才有效果
    tyle/border_width: 4             # 窗口边界宽度，大于圆角半径才有效果
    style/line_spacing: 1         # 候选词的行间距
    style/spacing: 5              # 在非内嵌编码模式下，预编辑和候选词之间的间距
    style/font_face: "Lantinghei TC Extralight"  # 预选栏文字字体，使用中文字体：兰亭黑-纤黑
    style/font_point: 17             #预选栏文字字号
    style/label_font_face: "Myriad Pro Light"  # 预选栏编号字体，使用西文字体：Myriad Pro Light
    style/label_font_point: 17       #预选栏编号字号
    app_options/com.runningwithcrayons.Alfred: 
      ascii_mode: true